language: node_js
node_js:
- 0.12
script:
- npm run-script build
deploy:
  provider: heroku
  api_key:
    secure: JUl2i80GN576JxGKuHzfuGBGmaUkNJaFgbmkYHp1wGxlr94+8/dvhHLJaM0nCZrFugceZjxg7Fe7Lfm14B66C+7Pn94nTt2lDirKhbNWCrz24KsJHUshbbYf5+mwH04kXOfpZTY01lsc+IhGPS/u4ollQ9RdZpywFNFn4G6P7bKQamLnhKEnxgr4bnRx9KKXccFtx5FiutuCfPYmUxx6bk066EoMMPs4obiRo+n7YPjLe2YbWwkfJa2NC88x3j73JDGaU/YNzHIYbKABQgeSTwYXGW82wvQ1MGr95Vfw6+W0to6n7XnVOeS/Bm2UwtVC0UPHPcMrcfjabA2Mg8IV2hrxz92OUYoOOowHMFAgOqmOS1KBMiw529HeWSdr40e5Kw6/BEM4GPuaO8fOvn0P6MlyGQwyguZW4pLrIj/YvxOlVTb0v0VjZ7FGuhni/tcx12+snZubeBBoXcTzXE0fvUN078o8xbd8+r/no0TOFZW/bG1gGflKfqTIhoS6WKD+EFYuoU5o8Sv9/JUBens1w/YXrJ18oyLL0D7E//VpGV7s0AO+q7rxxzW2fBh0ueN5a9+Vtvdh3o39lCCB5DP8K0ODxiCGlnEet0xaPn6eXMaTTgHFuNmR8f+qiQxaJkws8IfDKqHcv0543DVamzcMPmhE5eZabVLsRErIwJ3m2xM=
  app: got-stats
  on:
    repo: Rostlab/JS16_ProjectF
    all_branches: true
